name: Generate Snake Game

on:
  schedule:
    # Runs daily at 00:00 UTC
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # This action generates the snake SVG and commits it back to the repo
      - name: Generate Snake Game
        uses: danielguimaraes/github-contribution-grid-snake@v4.1.0 # This version is stable
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          github_user_name: TheGaush
          # The output path where the SVG is saved
          svg_out_path: dist/github-contribution-grid-snake.svg 

      # Push the changes (the new SVG file) back to the main branch
      - name: Push new SVG to repo
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Actions Bot
          author_email: actions@github.com
          message: 'feat(snake): Generate latest snake game SVG'
          add: 'dist/github-contribution-grid-snake.svg'
