name: Update Pacman Graph

on:
  schedule:
    # Runs daily at 00:00 UTC
    - cron: "0 0 * * *"
  # Allows you to manually trigger the action from the GitHub UI
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

     # This is the action that generates the Snake game graph
      - name: Generate Contribution Game
        uses: danielguimaraes/github-contribution-grid-snake@v4.1.0
        with:
          github_user_name: TheGaush
          # This action writes directly to the README.md
          svg_out_path: assets/github-contribution-grid-snake.svg
