name: Update Pacman Graph

on:
  schedule:
    # Runs daily at 00:00 UTC
    - cron: "0 0 * * *"
  # Allows you to manually trigger the action from the GitHub UI
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

     # Generates the snake game (the most reliable version)
      - uses: Platane/snk@v3 
        id: snake-gif
        with:
          github_user_name: TheGaush
          outputs: dist/github-contribution-grid-snake.svg
          # This ensures the action runs even if there's no contribution today
          cache: false

      # Pushes the generated snake SVG to your repository
      - uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: main
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
